# Generated by Django 5.1.3 on 2024-11-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastrar',
            fields=[
                ('usuario', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('senha', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('telefone', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mensagem', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('descricao', models.CharField(default='', max_length=1000)),
                ('preco', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('usuario', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('senha', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
