# Generated by Django 5.1.3 on 2024-11-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('descricao', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Exercicio',
            new_name='Planos',
        ),
    ]
